/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    pageNumber?: number;
                    pageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AccountDtoPagedResultApiResponse"];
                        "application/json": components["schemas"]["AccountDtoPagedResultApiResponse"];
                        "text/json": components["schemas"]["AccountDtoPagedResultApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{accountId}/lock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ObjectApiResponse"];
                        "application/json": components["schemas"]["ObjectApiResponse"];
                        "text/json": components["schemas"]["ObjectApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{accountId}/unlock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ObjectApiResponse"];
                        "application/json": components["schemas"]["ObjectApiResponse"];
                        "text/json": components["schemas"]["ObjectApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    pageNumber?: number;
                    pageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CustomerPagedResultApiResponse"];
                        "application/json": components["schemas"]["CustomerPagedResultApiResponse"];
                        "text/json": components["schemas"]["CustomerPagedResultApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CustomerProfileDto"];
                    "text/json": components["schemas"]["CustomerProfileDto"];
                    "application/*+json": components["schemas"]["CustomerProfileDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CustomerApiResponse"];
                        "application/json": components["schemas"]["CustomerApiResponse"];
                        "text/json": components["schemas"]["CustomerApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/customers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CustomerApiResponse"];
                        "application/json": components["schemas"]["CustomerApiResponse"];
                        "text/json": components["schemas"]["CustomerApiResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CustomerProfileDto"];
                    "text/json": components["schemas"]["CustomerProfileDto"];
                    "application/*+json": components["schemas"]["CustomerProfileDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CustomerApiResponse"];
                        "application/json": components["schemas"]["CustomerApiResponse"];
                        "text/json": components["schemas"]["CustomerApiResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    SearchTerm?: string;
                    ActorType?: components["schemas"]["ActorType"];
                    EntityName?: string;
                    Action?: string;
                    FromDate?: string;
                    ToDate?: string;
                    PageNumber?: number;
                    PageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuditDtoPagedResultApiResponse"];
                        "application/json": components["schemas"]["AuditDtoPagedResultApiResponse"];
                        "text/json": components["schemas"]["AuditDtoPagedResultApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RegisterDto"];
                    "text/json": components["schemas"]["RegisterDto"];
                    "application/*+json": components["schemas"]["RegisterDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ObjectApiResponse"];
                        "application/json": components["schemas"]["ObjectApiResponse"];
                        "text/json": components["schemas"]["ObjectApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LoginDto"];
                    "text/json": components["schemas"]["LoginDto"];
                    "application/*+json": components["schemas"]["LoginDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AccountDtoApiResponse"];
                        "application/json": components["schemas"]["AccountDtoApiResponse"];
                        "text/json": components["schemas"]["AccountDtoApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ObjectApiResponse"];
                        "application/json": components["schemas"]["ObjectApiResponse"];
                        "text/json": components["schemas"]["ObjectApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/issue-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CodeRequestDto"];
                    "text/json": components["schemas"]["CodeRequestDto"];
                    "application/*+json": components["schemas"]["CodeRequestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StringApiResponse"];
                        "application/json": components["schemas"]["StringApiResponse"];
                        "text/json": components["schemas"]["StringApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ResetPasswordDto"];
                    "text/json": components["schemas"]["ResetPasswordDto"];
                    "application/*+json": components["schemas"]["ResetPasswordDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ObjectApiResponse"];
                        "application/json": components["schemas"]["ObjectApiResponse"];
                        "text/json": components["schemas"]["ObjectApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AccountDtoApiResponse"];
                        "application/json": components["schemas"]["AccountDtoApiResponse"];
                        "text/json": components["schemas"]["AccountDtoApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BadmintonCourtPagedResultApiResponse"];
                        "application/json": components["schemas"]["BadmintonCourtPagedResultApiResponse"];
                        "text/json": components["schemas"]["BadmintonCourtPagedResultApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateCourtDto"];
                    "text/json": components["schemas"]["CreateCourtDto"];
                    "application/*+json": components["schemas"]["CreateCourtDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BadmintonCourtApiResponse"];
                        "application/json": components["schemas"]["BadmintonCourtApiResponse"];
                        "text/json": components["schemas"]["BadmintonCourtApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BadmintonCourtApiResponse"];
                        "application/json": components["schemas"]["BadmintonCourtApiResponse"];
                        "text/json": components["schemas"]["BadmintonCourtApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateCourtDto"];
                    "text/json": components["schemas"]["UpdateCourtDto"];
                    "application/*+json": components["schemas"]["UpdateCourtDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BadmintonCourtApiResponse"];
                        "application/json": components["schemas"]["BadmintonCourtApiResponse"];
                        "text/json": components["schemas"]["BadmintonCourtApiResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/courts/grid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    date?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CourtGridResponseDtoApiResponse"];
                        "application/json": components["schemas"]["CourtGridResponseDtoApiResponse"];
                        "text/json": components["schemas"]["CourtGridResponseDtoApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courts/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateCourtStatusDto"];
                    "text/json": components["schemas"]["UpdateCourtStatusDto"];
                    "application/*+json": components["schemas"]["UpdateCourtStatusDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BooleanApiResponse"];
                        "application/json": components["schemas"]["BooleanApiResponse"];
                        "text/json": components["schemas"]["BooleanApiResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/courts/{id}/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CourtScheduleListApiResponse"];
                        "application/json": components["schemas"]["CourtScheduleListApiResponse"];
                        "text/json": components["schemas"]["CourtScheduleListApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courts/{id}/schedules/{dayOfWeek}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                    dayOfWeek: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateCourtScheduleDto"];
                    "text/json": components["schemas"]["UpdateCourtScheduleDto"];
                    "application/*+json": components["schemas"]["UpdateCourtScheduleDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CourtScheduleApiResponse"];
                        "application/json": components["schemas"]["CourtScheduleApiResponse"];
                        "text/json": components["schemas"]["CourtScheduleApiResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    pageNumber?: number;
                    pageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AccountDtoPagedResultApiResponse"];
                        "application/json": components["schemas"]["AccountDtoPagedResultApiResponse"];
                        "text/json": components["schemas"]["AccountDtoPagedResultApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateEmployeeDto"];
                    "text/json": components["schemas"]["CreateEmployeeDto"];
                    "application/*+json": components["schemas"]["CreateEmployeeDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AccountDtoApiResponse"];
                        "application/json": components["schemas"]["AccountDtoApiResponse"];
                        "text/json": components["schemas"]["AccountDtoApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employees/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AccountDtoApiResponse"];
                        "application/json": components["schemas"]["AccountDtoApiResponse"];
                        "text/json": components["schemas"]["AccountDtoApiResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CustomerProfileDto"];
                    "text/json": components["schemas"]["CustomerProfileDto"];
                    "application/*+json": components["schemas"]["CustomerProfileDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AccountDtoApiResponse"];
                        "application/json": components["schemas"]["AccountDtoApiResponse"];
                        "text/json": components["schemas"]["AccountDtoApiResponse"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ObjectApiResponse"];
                        "application/json": components["schemas"]["ObjectApiResponse"];
                        "text/json": components["schemas"]["ObjectApiResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employees/{id}/lock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AccountDtoApiResponse"];
                        "application/json": components["schemas"]["AccountDtoApiResponse"];
                        "text/json": components["schemas"]["AccountDtoApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employees/{id}/unlock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AccountDtoApiResponse"];
                        "application/json": components["schemas"]["AccountDtoApiResponse"];
                        "text/json": components["schemas"]["AccountDtoApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courts/{id}/pricing-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PricingRuleListApiResponse"];
                        "application/json": components["schemas"]["PricingRuleListApiResponse"];
                        "text/json": components["schemas"]["PricingRuleListApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreatePricingRuleDto"];
                    "text/json": components["schemas"]["CreatePricingRuleDto"];
                    "application/*+json": components["schemas"]["CreatePricingRuleDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PricingRuleApiResponse"];
                        "application/json": components["schemas"]["PricingRuleApiResponse"];
                        "text/json": components["schemas"]["PricingRuleApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courts/{id}/pricing-rules/{pricingRuleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                    pricingRuleId: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdatePricingRuleDto"];
                    "text/json": components["schemas"]["UpdatePricingRuleDto"];
                    "application/*+json": components["schemas"]["UpdatePricingRuleDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PricingRuleApiResponse"];
                        "application/json": components["schemas"]["PricingRuleApiResponse"];
                        "text/json": components["schemas"]["PricingRuleApiResponse"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                    pricingRuleId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ObjectApiResponse"];
                        "application/json": components["schemas"]["ObjectApiResponse"];
                        "text/json": components["schemas"]["ObjectApiResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateProfileDto"];
                    "text/json": components["schemas"]["UpdateProfileDto"];
                    "application/*+json": components["schemas"]["UpdateProfileDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AccountDtoApiResponse"];
                        "application/json": components["schemas"]["AccountDtoApiResponse"];
                        "text/json": components["schemas"]["AccountDtoApiResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ChangePasswordDto"];
                    "text/json": components["schemas"]["ChangePasswordDto"];
                    "application/*+json": components["schemas"]["ChangePasswordDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ObjectApiResponse"];
                        "application/json": components["schemas"]["ObjectApiResponse"];
                        "text/json": components["schemas"]["ObjectApiResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/statistics/court-usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    fromDate?: string;
                    toDate?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BadmintonCourtListApiResponse"];
                        "application/json": components["schemas"]["BadmintonCourtListApiResponse"];
                        "text/json": components["schemas"]["BadmintonCourtListApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccountDto: {
            /** Format: uuid */
            accountId?: string;
            accountType?: components["schemas"]["AccountType"];
            status?: components["schemas"]["AccountStatus"];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            customer?: components["schemas"]["Customer"];
            employee?: components["schemas"]["Employee"];
        };
        AccountDtoApiResponse: {
            success?: boolean;
            data?: components["schemas"]["AccountDto"];
            message?: string | null;
            errors?: {
                [key: string]: string[];
            } | null;
        };
        AccountDtoPagedResult: {
            items?: components["schemas"]["AccountDto"][] | null;
            /** Format: int32 */
            pageNumber?: number;
            /** Format: int32 */
            pageSize?: number;
            /** Format: int32 */
            totalCount?: number;
            /** Format: int32 */
            readonly totalPages?: number;
        };
        AccountDtoPagedResultApiResponse: {
            success?: boolean;
            data?: components["schemas"]["AccountDtoPagedResult"];
            message?: string | null;
            errors?: {
                [key: string]: string[];
            } | null;
        };
        /** @enum {string} */
        AccountStatus: "Active" | "Disabled";
        /** @enum {string} */
        AccountType: "Customer" | "Employee";
        /** @enum {string} */
        ActorType: "System" | "Employee" | "Customer";
        AuditDto: {
            /** Format: int32 */
            id?: number;
            actorType?: components["schemas"]["ActorType"];
            /** Format: uuid */
            actorId?: string | null;
            actorName?: string | null;
            action?: string | null;
            entityName?: string | null;
            entityId?: string | null;
            oldValue?: string | null;
            newValue?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
        AuditDtoPagedResult: {
            items?: components["schemas"]["AuditDto"][] | null;
            /** Format: int32 */
            pageNumber?: number;
            /** Format: int32 */
            pageSize?: number;
            /** Format: int32 */
            totalCount?: number;
            /** Format: int32 */
            readonly totalPages?: number;
        };
        AuditDtoPagedResultApiResponse: {
            success?: boolean;
            data?: components["schemas"]["AuditDtoPagedResult"];
            message?: string | null;
            errors?: {
                [key: string]: string[];
            } | null;
        };
        BadmintonCourt: {
            /** Format: int32 */
            courtId?: number;
            name?: string | null;
            description?: string | null;
            status?: components["schemas"]["CourtStatus"];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            courtSchedules?: components["schemas"]["CourtSchedule"][] | null;
            pricingRules?: components["schemas"]["PricingRule"][] | null;
        };
        BadmintonCourtApiResponse: {
            success?: boolean;
            data?: components["schemas"]["BadmintonCourt"];
            message?: string | null;
            errors?: {
                [key: string]: string[];
            } | null;
        };
        BadmintonCourtListApiResponse: {
            success?: boolean;
            data?: components["schemas"]["BadmintonCourt"][] | null;
            message?: string | null;
            errors?: {
                [key: string]: string[];
            } | null;
        };
        BadmintonCourtPagedResult: {
            items?: components["schemas"]["BadmintonCourt"][] | null;
            /** Format: int32 */
            pageNumber?: number;
            /** Format: int32 */
            pageSize?: number;
            /** Format: int32 */
            totalCount?: number;
            /** Format: int32 */
            readonly totalPages?: number;
        };
        BadmintonCourtPagedResultApiResponse: {
            success?: boolean;
            data?: components["schemas"]["BadmintonCourtPagedResult"];
            message?: string | null;
            errors?: {
                [key: string]: string[];
            } | null;
        };
        BooleanApiResponse: {
            success?: boolean;
            data?: boolean;
            message?: string | null;
            errors?: {
                [key: string]: string[];
            } | null;
        };
        ChangePasswordDto: {
            currentPassword?: string | null;
            newPassword?: string | null;
            confirmNewPassword?: string | null;
        };
        CodeRequestDto: {
            email?: string | null;
            type?: components["schemas"]["CodeType"];
        };
        /** @enum {string} */
        CodeType: "VerifyEmail" | "ResetPassword";
        CourtDto: {
            /** Format: int32 */
            courtId?: number;
            name?: string | null;
            description?: string | null;
            status?: string | null;
            isInUse?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CourtGridItemDto: {
            court?: components["schemas"]["CourtDto"];
            slots?: components["schemas"]["CourtSlotDto"][] | null;
        };
        CourtGridResponseDto: {
            /** Format: date */
            date?: string;
            courts?: components["schemas"]["CourtGridItemDto"][] | null;
        };
        CourtGridResponseDtoApiResponse: {
            success?: boolean;
            data?: components["schemas"]["CourtGridResponseDto"];
            message?: string | null;
            errors?: {
                [key: string]: string[];
            } | null;
        };
        CourtSchedule: {
            /** Format: int32 */
            scheduleId?: number;
            /** Format: int32 */
            courtId?: number;
            /** Format: int32 */
            dayOfWeek?: number;
            /** Format: time */
            openTime?: string;
            /** Format: time */
            closeTime?: string;
            isAvailable?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CourtScheduleApiResponse: {
            success?: boolean;
            data?: components["schemas"]["CourtSchedule"];
            message?: string | null;
            errors?: {
                [key: string]: string[];
            } | null;
        };
        CourtScheduleListApiResponse: {
            success?: boolean;
            data?: components["schemas"]["CourtSchedule"][] | null;
            message?: string | null;
            errors?: {
                [key: string]: string[];
            } | null;
        };
        CourtSlotDto: {
            /** Format: int32 */
            courtId?: number;
            /** Format: date */
            date?: string;
            startTime?: string | null;
            endTime?: string | null;
            displayStatus?: string | null;
            /** Format: uuid */
            bookingId?: string | null;
            /** Format: double */
            pricePerHour?: number;
        };
        /** @enum {string} */
        CourtStatus: "Active" | "Maintenance" | "Closed";
        CreateCourtDto: {
            name?: string | null;
            description?: string | null;
            /** Format: time */
            defaultOpenTime?: string;
            /** Format: time */
            defaultCloseTime?: string;
            /** Format: double */
            defaultPricePerHour?: number;
        };
        CreateEmployeeDto: {
            fullName?: string | null;
            phone?: string | null;
            email?: string | null;
            password?: string | null;
            isAdmin?: boolean;
        };
        CreatePricingRuleDto: {
            /** Format: int32 */
            dayOfWeek?: number;
            /** Format: time */
            startTime?: string;
            /** Format: time */
            endTime?: string;
            /** Format: double */
            pricePerHour?: number;
        };
        Customer: {
            /** Format: uuid */
            customerId?: string;
            /** Format: uuid */
            accountId?: string | null;
            fullName?: string | null;
            phone?: string | null;
            email?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CustomerApiResponse: {
            success?: boolean;
            data?: components["schemas"]["Customer"];
            message?: string | null;
            errors?: {
                [key: string]: string[];
            } | null;
        };
        CustomerPagedResult: {
            items?: components["schemas"]["Customer"][] | null;
            /** Format: int32 */
            pageNumber?: number;
            /** Format: int32 */
            pageSize?: number;
            /** Format: int32 */
            totalCount?: number;
            /** Format: int32 */
            readonly totalPages?: number;
        };
        CustomerPagedResultApiResponse: {
            success?: boolean;
            data?: components["schemas"]["CustomerPagedResult"];
            message?: string | null;
            errors?: {
                [key: string]: string[];
            } | null;
        };
        CustomerProfileDto: {
            fullName?: string | null;
            phone?: string | null;
            email?: string | null;
        };
        Employee: {
            /** Format: uuid */
            employeeId?: string;
            /** Format: uuid */
            accountId?: string | null;
            fullName?: string | null;
            phone?: string | null;
            email?: string | null;
            isAdmin?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        LoginDto: {
            email?: string | null;
            password?: string | null;
        };
        ObjectApiResponse: {
            success?: boolean;
            data?: unknown;
            message?: string | null;
            errors?: {
                [key: string]: string[];
            } | null;
        };
        PricingRule: {
            /** Format: int32 */
            pricingRuleId?: number;
            /** Format: int32 */
            courtId?: number;
            /** Format: int32 */
            dayOfWeek?: number;
            /** Format: time */
            startTime?: string;
            /** Format: time */
            endTime?: string;
            /** Format: double */
            pricePerHour?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        PricingRuleApiResponse: {
            success?: boolean;
            data?: components["schemas"]["PricingRule"];
            message?: string | null;
            errors?: {
                [key: string]: string[];
            } | null;
        };
        PricingRuleListApiResponse: {
            success?: boolean;
            data?: components["schemas"]["PricingRule"][] | null;
            message?: string | null;
            errors?: {
                [key: string]: string[];
            } | null;
        };
        RegisterDto: {
            fullName?: string | null;
            phone?: string | null;
            email?: string | null;
            code?: string | null;
            password?: string | null;
            confirmPassword?: string | null;
        };
        ResetPasswordDto: {
            email?: string | null;
            code?: string | null;
            password?: string | null;
        };
        StringApiResponse: {
            success?: boolean;
            data?: string | null;
            message?: string | null;
            errors?: {
                [key: string]: string[];
            } | null;
        };
        UpdateCourtDto: {
            name?: string | null;
            description?: string | null;
        };
        UpdateCourtScheduleDto: {
            /** Format: time */
            openTime?: string;
            /** Format: time */
            closeTime?: string;
            isAvailable?: boolean;
        };
        UpdateCourtStatusDto: {
            status?: components["schemas"]["CourtStatus"];
            reason?: string | null;
        };
        UpdatePricingRuleDto: {
            /** Format: int32 */
            dayOfWeek?: number;
            /** Format: time */
            startTime?: string;
            /** Format: time */
            endTime?: string;
            /** Format: double */
            pricePerHour?: number;
        };
        UpdateProfileDto: {
            fullName?: string | null;
            phone?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
